name: fiber_predictor
channels:
  - defaults
  - conda-forge
  - pytorch
  
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - pillow
  - scikit-image
  - scikit-learn
  - torchvision
  - pytorch
  - pip
  - pip:
      - jupyter
      - -e .
